/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import modules.allmethods;
import modules.javaconnect;

/**
 *
 * @author ppp
 */
public class frmStudentLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmStudentLogin
     */
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    private SimpleDateFormat f1 = new SimpleDateFormat("hh:mm:ss");
    private SimpleDateFormat f2 = new SimpleDateFormat("aa");
    private SimpleDateFormat f3 = new SimpleDateFormat("dd MMMM yyyy - EEE");
    private Timer timer;
    private Date dateNow;
    
    public frmStudentLogin() {
        initComponents();
        Clock();
        conn= javaconnect.ConnecrDb();
        allmethods.Update_table(jTable1, "Select * from loginrecord_view");
    }
    
     private void Clock(){
        timer = new Timer(990, new dispTime());
	timer.start();
    }
    
    private void recordLogin(){
        try {
            String sql="Insert into tbl_studlogin(studid,loginDateTime) values(?,now())";
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_StudId.getText());
            pst.execute();
            allmethods.Update_table(jTable1, "Select * from loginrecord_view");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
    
    }
     
    private boolean logincheck(){
        
        try {
            String sql="Select studid from tbl_student where studid=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_StudId.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                return true;
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return false;
        
    }
      
       public class dispTime implements ActionListener{
        @Override
	public void actionPerformed(ActionEvent e){
		Calendar runningTime = Calendar.getInstance();
                dateNow = runningTime.getTime();
		lbltime.setText(f1.format(dateNow));
                lblsec.setText(f2.format(dateNow));
		lbldate.setText(f3.format(dateNow));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_StudId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblsec = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student ID");

        txt_StudId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StudIdActionPerformed(evt);
            }
        });
        txt_StudId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_StudIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_StudIdKeyReleased(evt);
            }
        });

        lbldate.setText("Date");

        lblsec.setText("jLabel3");

        lbltime.setText("jLabel3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_StudId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldate)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblsec)))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_StudId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsec)
                            .addComponent(lbltime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldate)))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_StudIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StudIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StudIdActionPerformed

    private void txt_StudIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StudIdKeyPressed
        // TODO add your handling co

    }//GEN-LAST:event_txt_StudIdKeyPressed

    private void txt_StudIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StudIdKeyReleased
        // TODO add your handling code here:
        String input=txt_StudId.getText();
        if(input.length()==6){
            if(logincheck()){
                recordLogin();
                txt_StudId.setText("");
            }else{
                    JOptionPane.showMessageDialog(null, "User not registered");
                    txt_StudId.setText("");
                }
     
        }
    }//GEN-LAST:event_txt_StudIdKeyReleased

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        txt_StudId.requestFocusInWindow();
    }//GEN-LAST:event_jTable1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    */
                UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
          }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStudentLogin().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblsec;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txt_StudId;
    // End of variables declaration//GEN-END:variables
}

