package forms;
import forms.frmStudentID;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ppp
 */
public class main_form extends javax.swing.JFrame {

    /**
     * Creates new form main_form
     */
    String semester;
    String schoolyear;
    Calendar cal = Calendar.getInstance();
    
    public main_form() {
        initComponents();

    }
    
    public main_form(String semester, String schoolyear){
        initComponents();
        this.semester=semester;
        this.schoolyear=schoolyear;
        lblSemester.setText(this.semester);
        lblSchoolYear.setText(this.schoolyear);
        
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSchoolYear = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuStudLogin = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mnuUtiliy = new javax.swing.JMenu();
        mnuStudent = new javax.swing.JMenuItem();
        mnuCourse = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuReport = new javax.swing.JMenuItem();
        mnuLibaryId = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Attendance");

        jLabel1.setText("Semester:");

        lblSemester.setText("jLabel2");

        jLabel3.setText("School Year:");

        lblSchoolYear.setText("lblSchoolYear");

        mnuFile.setText("File");

        mnuStudLogin.setText("Student Login");
        mnuStudLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStudLoginActionPerformed(evt);
            }
        });
        mnuFile.add(mnuStudLogin);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        mnuView.setText("View");
        jMenuBar1.add(mnuView);

        mnuUtiliy.setText("Utilities");

        mnuStudent.setText("Student");
        mnuStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStudentActionPerformed(evt);
            }
        });
        mnuUtiliy.add(mnuStudent);

        mnuCourse.setText("Course");
        mnuCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCourseActionPerformed(evt);
            }
        });
        mnuUtiliy.add(mnuCourse);

        jMenuItem2.setText("Semester");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuUtiliy.add(jMenuItem2);

        jMenuItem3.setText("School Year");
        mnuUtiliy.add(jMenuItem3);

        jMenuBar1.add(mnuUtiliy);

        jMenu1.setText("Report");

        mnuReport.setText("Monthly Report");
        mnuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportActionPerformed(evt);
            }
        });
        jMenu1.add(mnuReport);

        mnuLibaryId.setText("Libary ID");
        mnuLibaryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibaryIdActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLibaryId);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSemester)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblSchoolYear)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSemester)
                    .addComponent(jLabel3)
                    .addComponent(lblSchoolYear))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(844, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
         
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStudentActionPerformed
        // TODO add your handling code here:
        new frmStudent().setVisible(true);
       
    }//GEN-LAST:event_mnuStudentActionPerformed

    private void mnuLibaryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibaryIdActionPerformed
           // TODO add your handling code here:
        new frmStudentID().setVisible(true);
        
    }//GEN-LAST:event_mnuLibaryIdActionPerformed

    private void mnuCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCourseActionPerformed
        // TODO add your handling code here:
        new frmCourse().setVisible(true);
    }//GEN-LAST:event_mnuCourseActionPerformed

    private void mnuStudLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStudLoginActionPerformed
        // TODO add your handling code here:
        new frmStudentLogin().setVisible(true);
    }//GEN-LAST:event_mnuStudLoginActionPerformed

    private void mnuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportActionPerformed
        // TODO add your handling code here:
        new frmMonthlyReport().setVisible(true);
    }//GEN-LAST:event_mnuReportActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    */
                UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
                
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblSchoolYear;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JMenuItem mnuCourse;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuLibaryId;
    private javax.swing.JMenuItem mnuReport;
    private javax.swing.JMenuItem mnuStudLogin;
    private javax.swing.JMenuItem mnuStudent;
    private javax.swing.JMenu mnuUtiliy;
    private javax.swing.JMenu mnuView;
    // End of variables declaration//GEN-END:variables
}
